name: Web App CI

on:
  push:
    branches: [ main ]
    paths:
    - 'packages/web/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'packages/web/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
        working-directory: packages/web
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Create a production build
      run: yarn build
